<?php /** @var \ParadoxLabs\Subscriptions\Block\Customer\View\Buttons $block */ ?>
<?php // @codingStandardsIgnoreFile ?>

<div class="actions-toolbar subscription-actions-toolbar">
    <div class="actions">
        <?php if ($block->getStatusSource()->canSetStatus($block->getSubscription(), \ParadoxLabs\Subscriptions\Model\Source\Status::STATUS_CANCELED)): ?>
            <a class="action primary edit" href="<?php echo $block->getEditUrl(); ?>">
                <span><?php echo __('Edit'); ?></span>
            </a>
        <?php endif; ?>
        <?php if ($block->canPause($block->getSubscription())): ?>
            <a class="action secondary pause" href="<?php echo $block->getPauseUrl(); ?>">
            <span><?php echo __('Pause'); ?></span>
            </a>
        <?php endif; ?>
        <?php if ($block->canActivate($block->getSubscription())): ?>
            <a class="action secondary activate" href="<?php echo $block->getActivateUrl(); ?>">
                <span><?php echo __('Reactivate'); ?></span>
            </a>
        <?php endif; ?>
        <?php if ($block->canCancel($block->getSubscription())): ?>
            <a class="action secondary cancel" href="<?php echo $block->getCancelUrl(); ?>">
                <span><?php echo __('Cancel'); ?></span>
            </a>
        <?php endif; ?>
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>
