<?php
// @codingStandardsIgnoreFile
/** @var \ParadoxLabs\Subscriptions\Block\Customer\View\Items $block */
?>
<div class="subscription cart table-wrapper" data-mage-init='{"subscriptionsView":{}}'>
    <table id="subscription-item-table" class="subscription cart items data table">
        <caption role="heading" aria-level="2" class="table-caption"><?php echo __('Subscription Items') ?></caption>
        <thead>
        <tr>
            <th class="col item" scope="col"><span><?php echo __('Item') ?></span></th>
            <th class="col price" scope="col"><span><?php echo __('Price') ?></span></th>
            <th class="col qty" scope="col"><span><?php echo __('Qty') ?></span></th>
            <th class="col subtotal" scope="col"><span><?php echo __('Subtotal') ?></span></th>
        </tr>
        </thead>
        <?php foreach ($block->getItems() as $item): ?>
            <?php echo $block->getItemHtml($item) ?>
        <?php endforeach ?>
    </table>
</div>
