<?php
// @codingStandardsIgnoreFile
/** @var \ParadoxLabs\Subscriptions\Block\Customer\View\Logs $block */
?>
<?php if (count($this->getCollection()) > 0): ?>
    <div class="block block-subscription-info">
        <div class="block-title"><strong><?php echo __('History'); ?></strong></div>
        <div class="block-content">
            <div class="subscription logs table-wrapper" data-mage-init='{}'>
                <table id="subscription-log-table" class="subscription cart logs data table">
                    <caption role="heading" aria-level="2" class="table-caption"><?php echo __('Subscription History') ?></caption>
                    <thead>
                        <tr>
                            <th class="col date" scope="col"><span><?php echo __('Date') ?></span></th>
                            <th class="col order" scope="col"><span><?php echo __('Order #') ?></span></th>
                            <th class="col description" scope="col"><span><?php echo __('Description') ?></span></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php /** @var \ParadoxLabs\Subscriptions\Api\Data\LogInterface $log */ ?>
                        <?php foreach ($this->getCollection() as $log): ?>
                            <tr>
                                <td><?php echo $block->formatDate($log->getCreatedAt(), \IntlDateFormatter::MEDIUM); ?></td>
                                <td>
                                    <?php if ($log->getData('order_id') != ''): ?>
                                        <a href="<?php echo $block->getUrl('sales/order/view', ['order_id' => $log->getData('order_id')]); ?>">
                                            <?php echo $log->getOrderIncrementId(); ?>
                                        </a>
                                    <?php else: ?>
                                        -
                                    <?php endif; ?>
                                </td>
                                <td><?php echo $log->getDescription(); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php endif; ?>
